apiVersion: v1
kind: Service
metadata:
  name: cockroachdb
spec:
  clusterIP: None
  selector:
    app: cockroachdb
  ports:
    - name: grpc
      port: 26257
      targetPort: 26257
    - name: http
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb
spec:
  serviceName: cockroachdb
  replicas: 3

  selector:
    matchLabels:
      app: cockroachdb

  template:
    metadata:
      labels:
        app: cockroachdb

    spec:
      containers:
      - name: cockroachdb
        image: cockroachdb/cockroach:v25.1.0

        ports:
        - containerPort: 26257
          name: grpc

        - containerPort: 8080
          name: http

        command:
          - /bin/bash
          - -ecx
          - |
            exec cockroach start \
              --insecure \
              --join=cockroachdb-0.cockroachdb,cockroachdb-1.cockroachdb,cockroachdb-2.cockroachdb \
              --advertise-addr=$(hostname -f) \
              --http-addr=0.0.0.0:8080 \
              --cache=.25 \
              --max-sql-memory=.25

        volumeMounts:
        - name: datadir
          mountPath: /cockroach/cockroach-data

        resources:
          requests:
            cpu: "2"
            memory: 6Gi

          limits:
            cpu: "2"
            memory: 6Gi

  volumeClaimTemplates:
  - metadata:
      name: datadir

    spec:
      accessModes:
        - ReadWriteOnce

      storageClassName: ceph-hdd

      resources:
        requests:
          storage: 10Gi